### ISSUE TITLE
Idea: EPICS database and tmc file versioning synchronization

### ISSUE THREAD

**Issue by klauer** [pcdshub/pytmc#29]
Consider generating a read-only record with a unique identifier of the `.tmc` file + version:
* If in a *clean* git repository, `git describe --tags`
* (All/part of) the `.tmc` sha-sum or some other hash
* Something else?

**Comment by n-wbrown** [comment]
Additional information: 
 - Creation date
 - Author name?
 - If we end up in a situation where we have multiple EPICS ADS Module versions we could specify the version this file is intended to work with

**Comment by klauer** [comment]
We work around this by way of generating the version records inside the IOC startup script. It makes more sense than baking it into the database file, I think.

Closing as "fixed a different way"
