### ISSUE TITLE
EPICS database record sorting options (or the default?)

### ISSUE THREAD

**Issue by klauer** [pcdshub/pytmc#292]
Databases are generated from the order that pytmc discovers symbols inside the tmc file.

Some things:
* I had thought that the order was more stable than it is.
* Parts of it are often stable but other parts jiggle around depending on project rebuilds
* pytmc not having to find all symbols and sort them was considered a minor speedup

I'd vote to change this to either:
* Order records by the full twincat symbol name. (I think this could be more stable than PV name.)
* Order records by their name

**Comment by ZLLentz** [comment]
> Parts of it are often stable but other parts jiggle around depending on project rebuilds
This is kind of bizarre. I'm almost curious enough to figure out the specifics, but not quite.

I agree that the sorting is desirable despite the slowdown.

I think these two options would be similarly stable in practice, but nobody ever goes around asking to change variable names. So I think your thought that the full symbol name is more stable is correct.
