### ISSUE TITLE
lfe and kfe vac IOCs do not build

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pytmc#313]
Error is duplicate records

Need to investigate to see if there's a pytmc bug or if we somehow have production PLCs whose IOCs are broken

To reproduce:
- clone the repo
- update ads-ioc to latest
- `make` with `pytmc` at master

**Comment by ZLLentz** [comment]
After investigation, this might become an issue in those repos instead of this one

**Comment by klauer** [comment]
Duplicate records is typically a library versioning misconfiguration

https://confluence.slac.stanford.edu/display/PCDS/Beckhoff+Flight+Rules#BeckhoffFlightRules-pytmcreports%22duplicaterecords%22

Which records is it?

**Comment by ZLLentz** [comment]
It's general lib, so maybe it's just standard library misconfiguration + never built with modern ads-ioc/pytmc with duplicate checking?

**Comment by klauer** [comment]
That must be it (🤞 )

**Comment by ZLLentz** [comment]
lfe vac plc actually does build, I must have gotten confused
kfe vac is definitely the general lib thing and has the problem with latest tag as well as on master
issue created in kfe vac repo
